force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectTriggerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the SObject setting is active. Setting this as inactive will disable all trigger handlers for this sObject type.</description>
    <inlineHelpText>Whether or not the SObject setting is active. Setting this as inactive will disable all trigger handlers for this sObject type.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/trigger-framework/objects/SObjectTriggerSetting__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The type of SObject this setting is for (e.g. Account)</description>
    <inlineHelpText>The type of SObject this setting is for (e.g. Account)</inlineHelpText>
    <label>SObject Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler for each individual trigger handler (piece of business logic)</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the handler class that this configuration represents</description>
    <inlineHelpText>The name of the handler class that this configuration represents</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the trigger handler is active</description>
    <inlineHelpText>Whether or not the trigger handler is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The parent SObject setting</description>
    <inlineHelpText>The parent SObject setting</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/trigger-framework/classes/mocks/SObjectTriggerSettingSelectorMock.cls
/**
 * Mock for selectors to prevent coupling to existing metadata records
**/
@IsTest
public class SObjectTriggerSettingSelectorMock implements System.StubProvider {

    @TestVisible
    private Set<String> handlers {
        get {
            if (this.handlers == null) {
                this.handlers = new Set<String>();
            }
            return this.handlers;
        }
        set;
    }

    public SObjectTriggerSettingSelectorMock(Set<String> handlers) {
        this.handlers = handlers;
    }

    public Object handleMethodCall(
        Object stubbedObject, 
        String stubbedMethodName,
        Type returnType, 
        List<Type> listOfParamTypes, 
        List<String> listOfParamNames,
        List<Object> listOfArgs
    ) {
        switch on stubbedMethodName {
            when 'getSObjectTriggerSettings' {
                String sObjType = (String)listOfArgs[0];
                Map<String, Object> settingMap = new Map<String, Object>();
                settingMap.put('SObjectType__c', sObjType);
                Map<String, Object> handlers = new Map<String, Object>();
                handlers.put('totalSize', 1);
                handlers.put('done', true);
                List<Map<String, Object>> handlerObjects = new List<Map<String, Object>>();
                for (String handler : this.handlers) {
                    handlerObjects.add(new Map<String, Object> {
                        'IsActive__c' => true,
                        'ClassName__c' => handler
                    });
                }
                handlers.put('records', handlerObjects);
                settingMap.put('TriggerHandlerSettings__r', handlers);
                return new List<SObjectTriggerSetting__mdt> {
                    (SObjectTriggerSetting__mdt)JSON.deserialize(JSON.serialize(settingMap), SObjectTriggerSetting__mdt.class)
                };
            }
        }
        return null;
    }
}