force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler for each individual trigger handler (piece of business logic)</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the handler class that this configuration represents</description>
    <inlineHelpText>The name of the handler class that this configuration represents</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The parent SObject setting</description>
    <inlineHelpText>The parent SObject setting</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/trigger-framework/classes/TriggerDispatcherFactory.cls
/**
 * Factory class responsible for generating the trigger dispatcher for a provided sobject type
 */
public inherited sharing class TriggerDispatcherFactory {
    
    @TestVisible
    private static Map<String, List<ITriggerHandler>> loadedHandlers {
        get {
            if (loadedHandlers == null) {
                loadedHandlers = new Map<String, List<ITriggerHandler>>();
            }
            return loadedHandlers;
        }
        set;
    }

    @TestVisible
    private static SObjectTriggerSettingSelector selector {
        get {
            if (selector == null) {
                selector = new SObjectTriggerSettingSelector();
            }
            return selector;
        }
        set;
    }

    /**
     * Creates and returns a TriggerDispatcher for the provided SObjectType
     * @param sObjType Schema.SObjectType type of object to return dispatcher for
     * @param shouldThrowError whether or not the error should be added to the record, or if the error should
     * be bubbled up as a hard error. This has impacts details such as cleaner error messages, hiding stack trace details, etc.
     * @return TriggerDispatcher
     */
    public static TriggerDispatcher create(Schema.SObjectType sObjType, Boolean shouldThrowError) {
        String sObjTypeStr = String.valueOf(sObjType);
        List<ITriggerHandler> handlers;
        if (loadedHandlers.containsKey(sObjTypeStr)) {
            handlers = loadedHandlers.get(sObjTypeStr);
        } else {
            handlers = new List<ITriggerHandler>();
            List<SObjectTriggerSetting__mdt> settings = selector.getSObjectTriggerSettings(sObjTypeStr);
            // support multiple settings per sObject here in case you have multiple
            // settings split across multiple packages that get 
            for (SObjectTriggerSetting__mdt sObjectSetting : settings) {
                for (TriggerHandlerSetting__mdt handlerSetting : sObjectSetting.TriggerHandlerSettings__r) {
                    ITriggerHandler handler = (ITriggerHandler)Type.forName(handlerSetting.ClassName__c).newInstance();
                    handlers.add(handler);
                }
            }
            // place in a static var for reuse in the event of some amount of recursive dives
            // can potentially replace with a caching framework and hot swap static caches like this with
            // platform caches or other elements
            loadedHandlers.put(sObjTypeStr, handlers);
        }
        TriggerContext ctx = new TriggerContext();
        return new TriggerDispatcher(ctx, handlers, shouldThrowError);
    }
}