force-app/trigger-framework/objects/SObjectTriggerSetting__mdt/SObjectTriggerSetting__mdt.object-meta.xml
<CustomObject>
    <label>SObject Trigger Setting</label>
    <pluralLabel>SObject Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SObjectTriggerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the SObject setting is active. Setting this as inactive will disable all trigger handlers for this sObject type.</description>
    <inlineHelpText>Whether or not the SObject setting is active. Setting this as inactive will disable all trigger handlers for this sObject type.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/trigger-framework/objects/SObjectTriggerSetting__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <description>The type of SObject this setting is for (e.g. Account)</description>
    <inlineHelpText>The type of SObject this setting is for (e.g. Account)</inlineHelpText>
    <label>SObject Type</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/TriggerHandlerSetting__mdt.object-meta.xml
<CustomObject>
    <description>Handler for each individual trigger handler (piece of business logic)</description>
    <label>Trigger Handler Setting</label>
    <pluralLabel>Trigger Handler Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the handler class that this configuration represents</description>
    <inlineHelpText>The name of the handler class that this configuration represents</inlineHelpText>
    <label>Class Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the trigger handler is active</description>
    <inlineHelpText>Whether or not the trigger handler is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerHandlerSetting__mdt/fields/SObjectTriggerSetting__c.field-meta.xml
<CustomField>
    <fullName>SObjectTriggerSetting__c</fullName>
    <description>The parent SObject setting</description>
    <inlineHelpText>The parent SObject setting</inlineHelpText>
    <label>SObject Trigger Setting</label>
    <referenceTo>SObjectTriggerSetting__mdt</referenceTo>
    <relationshipLabel>Trigger Handler Settings</relationshipLabel>
    <relationshipName>TriggerHandlerSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/trigger-framework/classes/SObjectTriggerSettingSelector.cls
/**
 * Simple Selector for pulling in sObject Trigger Settings
 * Ideally in an enterprise org this would sit within a larger, more robust data access framework
**/
public inherited sharing class SObjectTriggerSettingSelector {
    /**
    * Returns the appropriate sobject trigger setting and related trigger 
    * handler settings for the provided sObjectType String
    * @param sObjType String representation of the sobject type to get settings for
    * @return List<SObjectTriggerSetting__mdt> 
    **/
    public List<SObjectTriggerSetting__mdt> getSObjectTriggerSettings(String sObjType) {
        // Custom metadata, no security check necessary
        return [
            SELECT SObjectType__c, (SELECT ClassName__c FROM TriggerHandlerSettings__r WHERE IsActive__c = true)
            FROM SObjectTriggerSetting__mdt
            WHERE SObjectType__c = :sObjType
            AND IsActive__c = true
        ];
    }
}